boot/urls.py
from django.urls import path

from boot import views

app_name = "boot"
urlpatterns = [
    path("base/",views.test),
    path("blog/",views.blog,name ="blog"),
    path("about/",views.about,name="about"),
    path("contact/",views.contact,name="contact"),
    path("home/",views.home,name="home"),
    path("inquiry/create/",views.inquiry_create),
    path("login/",views.login,name="login"),
    path("sign-up/",views.sign_up,name="sign_up"),
    path("logour/",views.logout,name="logout"),
]

demo_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from boot import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path("landing/", include("landing.urls")),
    path("boot/", include("boot.urls")),
    path("accounts/",include("allauth.urls")),
    # path("accounts/",include("allauth.socialaccount.providers.naver.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

landing/urls.py
from django.urls import path

from landing import views

app_name="landing"
urlpatterns = [
    path("index/",views.index,name="home"),
    path("create/",views.post_create, name="create"),
    path("read-all/",views.post_read_all, name="read-all"),
    path("read/<int:post_id>/",views.post_read, name="read"),
    path("update/<int:post_id>/",views.post_update, name="update"),
    path("delete/<int:post_id>/",views.post_delete, name="delete"),
    path("temptest/",views.temptest),
    path("path-test/<int:i><int:j>/",views.temptest, name="url_test")
    ]

boot/models.py
from email import message
from operator import truediv
from django.db import models

# Create your models here.

class Inquiry(models.Model):
    fullname  = models.CharField(max_length=32)
    email = models.CharField(max_length=32)
    phone_number = models.IntegerField()
    inquiry_message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self) -> str:
    #     return f"{self.id}.{self.title}"

landing/models.py
from operator import truediv
from django.db import models

# Create your models here.

class TempUser(models.Model):
    username = models.CharField(max_length=32)
    email = models.CharField(max_length=32)

class Post(models.Model):
    title  = models.CharField(max_length=32)
    content = models.TextField(blank=True, null=True)
    headimage = models.ImageField(
        upload_to="landing/images/%Y/%m/%d/%H/",
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # likes = models.IntegerField(default=0)
    writer = models.ForeignKey(
        TempUser, 
        on_delete=models.CASCADE,
        blank=True, null=True
        )

    liked_users = models.ManyToManyField(
        TempUser,
        related_name="user_likes" )

    def __str__(self) -> str:
        return f"{self.id}.{self.title}"

boot/views.py
from email import message
from pickle import GET
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

from boot.models import Inquiry

def test(request):
    return render (request,"base.html")

def blog(request):
    if not request.user.is_authenticated:
        return redirect("boot:login")
    return render (request,"boot/blog.html")

def about(request):
    return render (request,"boot/about.html")

def contact(request):
    return render (request,"boot/contact.html")

def home(request):
    print(request.user.is_authenticated)
    return render (request,"boot/home.html")

def inquiry_create(request):
    if request.method =="POST":
        fullname = request.POST.get("fullname")
        email = request.POST.get("email")
        phone_number = request.POST.get("phone_number")
        message = request.POST.get("message")

        new_inquiry=Inquiry()
        new_inquiry.fullname = fullname
        new_inquiry.email = email
        new_inquiry.phone_number = phone_number
        new_inquiry.inquiry_message = message
        new_inquiry.save()
    return redirect ("boot/home.html")

def login(request):
    if request.user.is_authenticated:
        return redirect("boot:home")
    context={}
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect("boot:home")
    
    return render (request,"boot/login.html",context=context)

def sign_up(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        password_check = request.POST.get("password_check")
        if username is not None and password is not None and password == password_check :
            new_user = User.objects.create_user(
                username = username,
                password=password,
            )
            return redirect("boot:login")
    return render (request,"boot/sign-up.html")

def logout(request):
    # print(request.user.is_authenticated)
    if request.method == "POST":
        auth.logout(request)
    return redirect("boot:home")

landing/views.py
import random
import re
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from landing.models import Post
from django.urls import reverse


def index(request):
    return render(request, "index.html")

def post_create(request):
    if request.method == "GET":
        return render(request,"landing/create.html")
    elif request.method == "POST":
        print(request.POST["title"])
        print(request.POST["content"])
        if request.FILES["image"]:
            print(request.FILES["image"])

        new_post = Post()
        new_post.title = request.POST["title"]
        new_post.content = request.POST["content"]
        if request.FILES["image"]:
            new_post.headimage = request.FILES["image"]
        new_post.save()

        return redirect('landing:read-all')

def post_read_all(request):
    post_list = Post.objects.all()
    # for post in post_list:
    #     print(post.content)
    context = {
        "posts" : post_list
    }
    # print(Post.objects.all())
    return render(request,"landing/read-all.html", context)

def post_read(request, post_id):
    print(post_id)
    post = Post.objects.get(id=post_id)
    context = {
        "post": post
    }
    return render(request,"landing/read.html",context)

# post_read랑 비슷한 구조의 함수 추가
# post_create의 함수 붙여넣기
def post_update(request,post_id):
    if request.method == "GET":
        post = Post.objects.get(id=post_id)
        context = {
            "post" : post,
        }
        return render(request,"landing/update.html",context)
    elif request.method == "POST":
        target_post = Post.objects.get(id=post_id)
        target_post.title = request.POST["title"]
        target_post.content = request.POST["content"]
        target_post.save()
        return HttpResponseRedirect(f"/landing/read/{post_id}")


def post_delete(request,post_id):
    if request.method == "GET":
        post = Post.objects.get(id=post_id)
        context = {
            "post" : post
        }
        return render(request,"landing/delete.html",context)
    elif request.method =="POST":
        target_post = Post.objects.get(id=post_id)
        target_post.delete()
        return HttpResponseRedirect("/landing/read-all/")

        
def temptest(request):
    context = {
        "temperature": 15,
        "weather" : {
        "weather" : "흐림",
        "temperature" : 30
        },

        "football_players": [ 
            {
                "name" : "손흥민",
                "team" : "토트넘"
            },

            {
                "name" : "리오넬 메시",
                "team" : "파리 생제르망"
            },

            {
                "name" : "이강인",
                "team" : "마요르카"
            }
        ]
    }

    return render(request,"landing/temptest.html",context)

boot/templates/boot/about.html
{% extends "base.html" %}
{% block title %}About{% endblock %}
{% block active_about %}active{% endblock %}
{% block main %}
            <header class="py-5">
                <div class="container px-5">
                    <div class="row justify-content-center">
                        <div class="col-lg-8 col-xxl-6">
                            <div class="text-center my-5">
                                <h1 class="fw-bolder mb-3">Our mission is to make building websites easier for everyone.</h1>
                                <p class="lead fw-normal text-muted mb-4">Start Bootstrap was built on the idea that quality, functional website templates and themes should be available to everyone. Use our open source, free products, or support us by purchasing one of our premium products or services.</p>
                                <a class="btn btn-primary btn-lg" href="#scroll-target">Read our story</a>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- About section one-->
            <section class="py-5 bg-light" id="scroll-target">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Our founding</h2>
                            <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- About section two-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    <div class="row gx-5 align-items-center">
                        <div class="col-lg-6 order-first order-lg-last"><img class="img-fluid rounded mb-5 mb-lg-0" src="https://dummyimage.com/600x400/343a40/6c757d" alt="..." /></div>
                        <div class="col-lg-6">
                            <h2 class="fw-bolder">Growth &amp; beyond</h2>
                            <p class="lead fw-normal text-muted mb-0">Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto est, ut esse a labore aliquam beatae expedita. Blanditiis impedit numquam libero molestiae et fugit cupiditate, quibusdam expedita, maiores eaque quisquam.</p>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Team members section-->
            <section class="py-5 bg-light">
                <div class="container px-5 my-5">
                    <div class="text-center">
                        <h2 class="fw-bolder">Our team</h2>
                        <p class="lead fw-normal text-muted mb-5">Dedicated to quality and your success</p>
                    </div>
                    <div class="row gx-5 row-cols-1 row-cols-sm-2 row-cols-xl-4 justify-content-center">
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Ibbie Eckart</h5>
                                <div class="fst-italic text-muted">Founder &amp; CEO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-xl-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Arden Vasek</h5>
                                <div class="fst-italic text-muted">CFO</div>
                            </div>
                        </div>
                        <div class="col mb-5 mb-5 mb-sm-0">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Toribio Nerthus</h5>
                                <div class="fst-italic text-muted">Operations Manager</div>
                            </div>
                        </div>
                        <div class="col mb-5">
                            <div class="text-center">
                                <img class="img-fluid rounded-circle mb-4 px-4" src="https://dummyimage.com/150x150/ced4da/6c757d" alt="..." />
                                <h5 class="fw-bolder">Malvina Cilla</h5>
                                <div class="fst-italic text-muted">CTO</div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>
       {% endblock %}

boot/templates/boot/blog.html
{% extends "base.html" %}
{% block title %}Blog Home{% endblock %}
{% block active_blog %}active{% endblock %}
{% block main %}
        <header class="py-5 bg-light border-bottom mb-4">
            <div class="container">
                <div class="text-center my-5">
                    <h1 class="fw-bolder">Welcome to Blog Home!</h1>
                    <p class="lead mb-0">A Bootstrap 5 starter layout for your next blog homepage</p>
                </div>
            </div>
        </header>
        <!-- Page content-->
        <div class="container">
            <div class="row">
                <!-- Blog entries-->
                <div class="col-lg-8">
                    <!-- Featured blog post-->
                    <div class="card mb-4">
                        <a href="#!"><img class="card-img-top" src="https://dummyimage.com/850x350/dee2e6/6c757d.jpg" alt="..." /></a>
                        <div class="card-body">
                            <div class="small text-muted">January 1, 2022</div>
                            <h2 class="card-title">Featured Post Title</h2>
                            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
                            <a class="btn btn-primary" href="#!">Read more →</a>
                        </div>
                    </div>
                    <!-- Nested row for non-featured blog posts-->
                    <div class="row">
                        <div class="col-lg-6">
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2022</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2022</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2022</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                            <!-- Blog post-->
                            <div class="card mb-4">
                                <a href="#!"><img class="card-img-top" src="https://dummyimage.com/700x350/dee2e6/6c757d.jpg" alt="..." /></a>
                                <div class="card-body">
                                    <div class="small text-muted">January 1, 2022</div>
                                    <h2 class="card-title h4">Post Title</h2>
                                    <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam.</p>
                                    <a class="btn btn-primary" href="#!">Read more →</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Pagination-->
                    <nav aria-label="Pagination">
                        <hr class="my-0" />
                        <ul class="pagination justify-content-center my-4">
                            <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Newer</a></li>
                            <li class="page-item active" aria-current="page"><a class="page-link" href="#!">1</a></li>
                            <li class="page-item"><a class="page-link" href="#!">2</a></li>
                            <li class="page-item"><a class="page-link" href="#!">3</a></li>
                            <li class="page-item disabled"><a class="page-link" href="#!">...</a></li>
                            <li class="page-item"><a class="page-link" href="#!">15</a></li>
                            <li class="page-item"><a class="page-link" href="#!">Older</a></li>
                        </ul>
                    </nav>
                </div>
                <!-- Side widgets-->
                <div class="col-lg-4">
                    <!-- Search widget-->
                    <div class="card mb-4">
                        <div class="card-header">Search</div>
                        <div class="card-body">
                            <div class="input-group">
                                <input class="form-control" type="text" placeholder="Enter search term..." aria-label="Enter search term..." aria-describedby="button-search" />
                                <button class="btn btn-primary" id="button-search" type="button">Go!</button>
                            </div>
                        </div>
                    </div>
                    <!-- Categories widget-->
                    <div class="card mb-4">
                        <div class="card-header">Categories</div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">Web Design</a></li>
                                        <li><a href="#!">HTML</a></li>
                                        <li><a href="#!">Freebies</a></li>
                                    </ul>
                                </div>
                                <div class="col-sm-6">
                                    <ul class="list-unstyled mb-0">
                                        <li><a href="#!">JavaScript</a></li>
                                        <li><a href="#!">CSS</a></li>
                                        <li><a href="#!">Tutorials</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Side widget-->
                    <div class="card mb-4">
                        <div class="card-header">Side Widget</div>
                        <div class="card-body">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

boot/templates/boot/sign-up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}

{% block main %}
<main class="flex-shrink-0">
    <!-- Page content-->
    <section class="py-5">
        <div class="container px-5">
            <!-- Contact form-->
            <div class="bg-light rounded-3 py-5 px-4 px-md-5">
                <div class="text-center mb-5">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                    <h1 class="fw-bolder">Sign Up</h1>
                    <!-- <p class="lead fw-normal text-muted mb-0">We'd love to hear from you</p> -->
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-8 col-xl-6">
                        <form id="login-form" action="{% url 'boot:sign_up' %}" method="post">
                            {% csrf_token %}
                            <!-- Name input-->
                            <div class="form-floating mb-3">
                                <input name="username" class="form-control" id="username" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                <label for="username">Username</label>
                            </div>
                            <!-- Password input-->
                            <div class="form-floating mb-3">
                                <input name="password" class="form-control" id="password" type="password" placeholder="********" data-sb-validations="required" />
                                <label for="password">Password</label>
                            </div>
                            <!-- Password Check input-->
                            <div class="form-floating mb-3">
                                <input name="password_check" class="form-control" id="password_check" type="password" placeholder="********" data-sb-validations="required" />
                                <label for="password_check">Password Check</label>
                            </div>
                            <!-- Submit Button-->
                            <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Sign Up</button></div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- Contact cards-->
            <!-- <div class="row gx-5 row-cols-2 row-cols-lg-4 py-5">
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-chat-dots"></i></div>
                    <div class="h5 mb-2">Chat with us</div>
                    <p class="text-muted mb-0">Chat live with one of our support specialists.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-people"></i></div>
                    <div class="h5">Ask the community</div>
                    <p class="text-muted mb-0">Explore our community forums and communicate with other users.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-question-circle"></i></div>
                    <div class="h5">Support center</div>
                    <p class="text-muted mb-0">Browse FAQ's and support articles to find solutions.</p>
                </div>
                <div class="col">
                    <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-telephone"></i></div>
                    <div class="h5">Call us</div>
                    <p class="text-muted mb-0">Call us during normal business hours at (555) 892-9403.</p>
                </div>
            </div> -->
        </div>
    </section>
</main>
{% endblock %}

landing/templates/landing/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post create</title>
</head>
<body>
    <form 
        action="{% url 'landing:create' %}" 
        id="post-write" 
        method="post"
        enctype="multipart/form-data"
        >
        {% csrf_token %}
        title: <input type="text" name="title" value="title hello">
        <div>
            <input type="file" name="image">
        </div>
        <input type="submit" value="GO">

    </form>
    <textarea name="content" form="post-write">Enter Text Here...</textarea>
</body>
</html>

landing/templates/landing/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Delete</title>
</head>
<body>
    <p>Delete: {{ Post.title }}?</p>
    <form action="{% url 'landing:delete' post.id %}" method="post">
        {% csrf_token %}
        <input type="submit" value="YES">
    </form>
    <form action="{% url 'landing:read' post.id %}" method="get">
        {% csrf_token %}
        <input type="submit" value="NO">
    </form>
</body>
</html>

landing/templates/landing/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    HELLO WORKS!
</body>
</html>

landing/templates/landing/read-all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Read All</title>
</head>
<body>
    {% if posts %}
    <ul>
        {% for post in posts %}
        <li><a href="{% url 'landing:read' post.id %}">{{ post.title }}</a></li>
        {% empty %}
        <li>아직 작성된 글이 없습니다</li>
        {% endfor %}
        
    </ul>
    <!-- {% else %}
     이건 HTML 주석입니다.
    {# 이건 Django Template 주석입니다. #}
    <p>아직 작성된 글이 없습니다.</p>
    {% endif %} -->
        <a href="{% url 'landing:create' %}">게시글 작성</a>
</body>
</html>



<!-- <form action="/landing/create/" id="post-write" method="post">
    {% csrf_token %}
    title: <input type="text" name="title" value="title hello">
    <input type="submit" value="GO">
</form> -->

landing/templates/landing/read.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Read</title>
</head>
<body>
    <h1>{{ post.title }}</h1>
    {% if post.headimage %}
    <div>
        <img src="{{ post.headimage.url }}">
    </div>
    {% endif %}
    <p>{{ post.content }}</p>
    <div>
        <a href="{% url 'landing:update' post.id %}">Edit</a>
    </div>
    <div>
        <a href="{% url 'landing:delete' post.id %}">Delete</a>
    </div>
</body>
</html>

landing/templates/landing/temptest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>오늘의 날씨는 {{ weather }}이며, 온도는 섭씨 {{ temperature }}도 입니다.</p>
    <p>오늘의 날씨는 {{ weather_data.weather }}이며, 온도는 섭씨 {{ weather_data.temperature }}도 입니다.</p>
    <ul>
        {% for players in football_players %}
        <!-- <li>{{ football_players.0.name }}은 {{ football_players.0.team }}</li>
        <li>{{ football_players.1.name }}은 {{ football_players.1.team }}</li>
        <li>{{ football_players.2.name }}은 {{ football_players.2.team }}</li> -->
        <li>{{ players.name }}는 {{ players.team }}</li>
        {% endfor %}
        {% for player in baseball_players %}
        {{ player.name }}은 {{ player.team }} 소속입니다.
        {% empty %}
        야구 선수는 없습니다...
        {% endfor %}
    </ul>
    <p>
        <!-- 오늘의 기온은
        {% if not weather.temperature %}
        알 수 없습니다.
        {% elif weather.temperature < 10 %}
        {{ weather.temperature }}도 이며, 매우 춥습니다.
        {% elif weather.temperature > 30 %}
        {{ weather.temperature }}도 이며, 매우 덥습니다.
        {% else %}
        {{ weather.temperature }}도 이며, 매우 애매합니다.
        {% endif %} -->
        <!-- {% lorem 3 p random %} -->
        {% now "jS F Y H:i" %} <br>
        {% now "Y-n-j" %} <br>
        I know {{ football_players|length }} football players!
        
    
    </p>
    <h1>{% url 'landing:home' %}</h1>
</body>
</html>

landing/templates/landing/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post create</title>
</head>
<body>
    <form action="{% url 'landing:update' post.id %}" id="post-edit" method="post">
        {% csrf_token %}
        title: <input type="text" name="title" value="{{ post.title }}">
        <input type="submit" value="GO">
    </form>
    <textarea name="content" form="post-edit">{{ post.content }}</textarea>
</body>
</html>